// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who started the input that an assistant item responds to.
 *
 * This is display metadata only. It never enters model-visible context.
 */
export type ItemOrigin = "typed" | "voice";
