// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeReservationProfile } from "./NativeReservationProfile";
import type { NativeReservationState } from "./NativeReservationState";

/**
 * Native capacity preconditions only; never external model/framing qualification.
 */
export type NativeReservation = { generation: bigint, state: NativeReservationState, model: string | null, profile: NativeReservationProfile, usableContextTokens: bigint | null, reservedTokens: number, maxFrameBytes: number, };
