// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservationFrame } from "./ObservationFrame";

/**
 * Required nullable value: omitting `frame` must not silently clear a slot.
 */
export type ObservationFrameUpdate = ObservationFrame | null;
