// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObservationFrame = { text: string, hash: string,
/**
 * Unix seconds. Native admission validates the bounded active lease.
 */
expiresAt: bigint, };
