// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PilotNativeUsage } from "./PilotNativeUsage";

export type PilotNativeAttempt = { decisionId: string, attemptId: string, requestId: string, turnId: string, admissionRequestId: string | null, tokenCeiling: bigint, credentialReceipt: string, contextReceipt: string, responseId: string | null, usage: PilotNativeUsage | null, responseComplete: boolean, usageConflict: boolean, };
