// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservationReplacement } from "./ObservationReplacement";

export type ThreadObservationCapabilities = { protocol: number, ownerEpoch: string, maxFrameBytes: number, reservedTokens: number, maxLeaseSeconds: number, maxInFlightDecisions: number, replacement: ObservationReplacement, automaticAdmission: boolean, };
