// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservationCaptureState } from "./ObservationCaptureState";
import type { ObservationSubmissionOutcome } from "./ObservationSubmissionOutcome";

export type ThreadObservationSubmittedNotification = { threadId: string, turnId: string, ownerEpoch: string, decisionId: string, attemptId: string,
/**
 * Native wire-request identity, not a fabricated upstream ID.
 */
requestId: string, providerRequestId: string | null, commitOrder: bigint, frameRevision: bigint, frameHash: string | null, state: ObservationCaptureState, capturedAt: bigint, outcome: ObservationSubmissionOutcome, terminalDecision: boolean, };
