// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservationCaptureState } from "./ObservationCaptureState";

export type ThreadObservationCapturedNotification = { threadId: string, turnId: string, ownerEpoch: string, decisionId: string, commitOrder: bigint, frameRevision: bigint, frameHash: string | null, state: ObservationCaptureState,
/**
 * Native per-decision capture time, in Unix seconds; not host composition time.
 */
capturedAt: bigint, };
