// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Original host cooldown provenance, never permission or budget authority.
 */
export type WakeHostPreparation = { cooldownRevision: number,
/**
 * Exactly sixteen lowercase hex digits of the original positive finite binary64.
 */
wakeNotBeforeBits: string, };
