// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WakeHostPreparation } from "./WakeHostPreparation";

export type WakeReadQuery = { "type": "attempt", sequence: number, operandDigest: string, hostPreparation: WakeHostPreparation, } | { "type": "fence", sequence: number, };
